### ISSUE TITLE
Dropped: Package Objects page is reachable but cannot be navigated to

### ISSUE THREAD

**Issue by felix-hedenstrom** [lampepfl/dotty#24126]
I noticed that the page https://docs.scala-lang.org/scala3/reference/dropped-features/package-objects.html can still be navigated to through search engines even though it does not appear in the list of "dropped features" normally. 

I would expect it to either be listed among dropped features or for the page to not exist at all.

**Comment by WojciechMazur** [comment]
It's not listed in the index file on language-reference-stable branch from which it's generated so it should not be present: 
https://github.com/scala/scala3/blob/4f51b2744659b9bb9c6367cfad38ea30a17f8613/project/resources/referenceReplacements/sidebar.yml#L116-L138 

At the same time it's still listed in 3.7.3 branch which currently should be exactly the same as the one in language-reference-stable, so there is something wrong with synchronization. 
https://github.com/scala/scala3/blob/eb198cfad4876e812699821583548e0730eaf051/project/resources/referenceReplacements/sidebar.yml#L112-L122 

It might either be fixed by #23606 or maybe there is some issue in publishing workflow that keeps previously removed files.  

On the other hand reference documentation has some adjustments to make the links stable, so to some extent it might be beneficial.

**Comment by felix-hedenstrom** [comment]
Just wanted to mention that this is still happening. Are the changes from #23606 deployed?

**Comment by WojciechMazur** [comment]
You should not be able to find it in the menu, the PR linked above would prevent cases like that in the future

**Comment by felix-hedenstrom** [comment]
Maybe I don't understand the intent of the page.

When I search "Package objects scala 3" on google I find the page, yet it cannot be navigated to if I start out on https://docs.scala-lang.org/scala3/reference/.

I can understand leaving the page up to not kill hotlinks to it, but I think it should be clear if the page is still considered valid. If Scala 3 still intends to drop package objects I would expect this to be something I can determine based on the "Dropped Features" list in the reference. I cannot do this currently so I assume that it is not intended to be dropped. 

If the feature is not intended to be dropped it is unfortunate that it is the first result when googling "package object scala 3" and it is also unfortunate that the page you click on gives no indication that the contents are no longer relevant.

Feels like there is a lot of possibility for user confusion here.

<img width="958" height="408" alt="Image" src="https://github.com/user-attachments/assets/fed0adb8-9579-4057-b93f-5c4625fe7070" />

<img width="993" height="433" alt="Image" src="https://github.com/user-attachments/assets/3da55719-0c99-4073-8102-73cf03c4745b" />

**Comment by WojciechMazur** [comment]
Current reference now contains the package objects in the list 

<img width="278" height="326" alt="Image" src="https://github.com/user-attachments/assets/e88e7d69-f53a-4f7e-96fc-04a1fc119059" />

There is not yet any exact version planned when package object would be actually dropped. These are discouraged now and would eventually we dropped in some future version.
