### ISSUE TITLE
Assigning to val and then returning the ref causes ClassCastException

### ISSUE THREAD

**Issue by ekrich** [lampepfl/dotty#7357]
## minimized code

Assigning to an intermediate `val` or `var` causes a Runtime exception. Removing the intermediate works fine and the same as `2.11` - `2.13` with an intermediate `val`.

This is not a blocker but could affect others in the future. Workaround is to remove the `val` if able.

```Scala
object ClassCast {
  def main(args: Array[String]): Unit = {
    println(ClassCast.run())
  }

  import java.{lang => jl}
  enum ConfigValueType extends jl.Enum[ConfigValueType] {
    case OBJECT, LIST, NUMBER, BOOLEAN, NULL, STRING
  }

  class Config() {
    val map = new java.util.HashMap[String, Any]()
    map.put("foo", ConfigValueType.OBJECT)
    def getDouble(str: String): Double = ???
    def getInt(str: String): Int = ???
    def getString(str: String): String = ???
    def getEnum[T <: jl.Enum[T]](enumClass: Class[T], path: String): T = map.get(path).asInstanceOf
    def getBoolean(str: String): Boolean = ???
  }

  private def getEnumAsClass[T <: jl.Enum[T]](
      parameterClass: Class[_]): Class[T] =
    parameterClass.asInstanceOf[Class[T]]

  def getValue(parameterClass: Class[_],
                       config: Config,
                       configPropName: String): Any =
    if ((parameterClass == classOf[jl.Boolean]) || (parameterClass == classOf[
          Boolean])) config.getBoolean(configPropName)
    else if ((parameterClass == classOf[Integer]) || (parameterClass == classOf[
               Int]))
      config.getInt(configPropName)
    else if ((parameterClass == classOf[jl.Double]) || (parameterClass == classOf[
               Double])) config.getDouble(configPropName)

    else if (parameterClass == classOf[String])
      config.getString(configPropName)
    else if (parameterClass.isEnum) {
      // *** assigning to val and returning causes ClassCastException
      // returning directly works
      val e = config.getEnum(getEnumAsClass(parameterClass), configPropName)
      e
    } else {
      throw new Exception(
        "Bean property " + configPropName)
    }
  def run(): Any = {
    getValue(classOf[ConfigValueType], new Config(), "foo")
  }
}
```

## expectation

Should work as expected with the intermediate `val`. 

Expected output
```Scala
[info] Running Main 
OBJECT
```

## current output

```Scala
[info] Running ClassCast 
[error] (run-main-9) java.lang.ClassCastException: ClassCast$$anon$1 cannot be cast to scala.runtime.Nothing$
[error] java.lang.ClassCastException: ClassCast$$anon$1 cannot be cast to scala.runtime.Nothing$
[error] 	at ClassCast$.getValue(Main.scala:53)
[error] 	at ClassCast$.run(Main.scala:60)
[error] 	at ClassCast$.main(Main.scala:16)
[error] 	at ClassCast.main(Main.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1

```

**Comment by smarter** [comment]
I don't think there's a bug here, in:
```scala
config.getEnum(getEnumAsClass(parameterClass), configPropName)
```
we need to infer a type forr the type parameter `T` of `getEnum`, the only constraints we have is that `T` is a subtype of `Enum[T]` and the type of `parameterClass` must be a subtype of `Class[T]`, since `parameterClass` has type `Class[_]` that doesn't actually add any constraint, so `T := Nothing` is a valid solution.

This then leads to a crash because the definition of `getEnum` uses `asInstanceOf` which is unsafe.

**Comment by ekrich** [comment]
I’m not sure you should close this that quickly. The method should return a subclass of Enum[T] and the outer method should return Any and a T <: Enum[T] should be a subclass of Any. Not sure why we should get the bottom class as Nothing is a subclass of last resort.

Besides, only Dotty comes to this conclusion. Also, this is a slightly generated solution to demonstrate the problem not the actual code. I can debug in Scala 2 to find its current solution if needed. The solution of the val or var type needs to be consistent with the return type since that is the reference returned.

**Comment by ekrich** [comment]
Also, the getEnumAsClass method was added to make Dotty work. The original code would not compile as I recall.

**Comment by ekrich** [comment]
One other thing. We also have this issue that could be related. https://github.com/lampepfl/dotty/issues/7174
I did see Lazy[Enum] or some such thing during my typing struggles in that area.

**Comment by smarter** [comment]
Nothing is a subtype of everything, so I don't see why it wouldn't be a valid solution here. The bottom line is that if you use asInstanceOf, you're doing something unsafe and the compiler can't guarantee you won't get ClassCastException. The fact that inference works slightly differently in scala 2 is not enough for us to change anything here, it's impossible for Dotty type inference to work exactly the way Scala 2 does. If there is some other underlying problem here that lead you down this road of using asInstanceOf, then please open an issue for that.

**Comment by ekrich** [comment]
@smarter I updated my code above to show the problem better - with the code commented out that assigns to `val/var` this works fine. This is also just a minimization of code that seems to work fine so the cast which I changed should be safe anyway in the real API. 

I also think this could be a manifestation of another problem we talked about earlier related to hand rolled pre-Dotty enums that extend `Enum[T]` that did not compile in Dotty. I went with separate source for Dotty to take advantage of the `enum` goodness and workaround the problem I had earlier. Reference: https://github.com/lampepfl/dotty/issues/7390

**Comment by smarter** [comment]
>  with the code commented out that assigns to val/var this works fine

Yes, because when you're assigning to a val with no result type, type inference will proceed differently since it's less constrained, this does not change the fact that choosing `T := Nothing` is a _valid solution_, the bug is still to do an unsafe cast `asInstanceOf[T]` in a situation where you're not guaranteed that the value you cast is in fact a subtype of `T`.

**Comment by ekrich** [comment]
Ok, I edited the code once more with essentially the actual implementation.
```Scala
def getEnum[T <: jl.Enum[T]](enumClass: Class[T], path: String): T =
      jl.Enum.valueOf(enumClass, path)
```
Adding the type ascription as follows then works.
```Scala
var e: Enum = config.getEnum(getEnumAsClass(parameterClass), configPropName)
// or `jl.Enum[_]` works as well.
e
```
@smarter and @hrhino Are you both ok with this? If so then I am too. 

I sure wish that would fail at compile time rather than run time.

**Comment by smarter** [comment]
> I sure wish that would fail at compile time rather than run time.

It doesn't because you still have an unsafe, unsound cast:
```scala
  private def getEnumAsClass[T <: jl.Enum[T]](
      parameterClass: Class[_]): Class[T] =
    parameterClass.asInstanceOf[Class[T]]
```
This doesn't directly lead to a crash at runtime since the type parameter is erased, but you use this to call getEnum which tries to return a value based on that type parameter.

The conclusion is still the same, don't use `asInstanceOf` if you're not 100% sure that the type of the value you're casting is a subtype of the type you're casting to.
